# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/afedy/Source/Repos/photospline

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/afedy/Source/Repos/photospline

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/afedy/Source/Repos/photospline/CMakeFiles /mnt/c/Users/afedy/Source/Repos/photospline/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/afedy/Source/Repos/photospline/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named photospline-test-fit

# Build rule for target.
photospline-test-fit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-test-fit
.PHONY : photospline-test-fit

# fast build rule for target.
photospline-test-fit/fast:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/build
.PHONY : photospline-test-fit/fast

#=============================================================================
# Target rules for targets named spglam

# Build rule for target.
spglam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spglam
.PHONY : spglam

# fast build rule for target.
spglam/fast:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/build
.PHONY : spglam/fast

#=============================================================================
# Target rules for targets named cphotospline

# Build rule for target.
cphotospline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cphotospline
.PHONY : cphotospline

# fast build rule for target.
cphotospline/fast:
	$(MAKE) -f CMakeFiles/cphotospline.dir/build.make CMakeFiles/cphotospline.dir/build
.PHONY : cphotospline/fast

#=============================================================================
# Target rules for targets named photospline-gen_test_splines

# Build rule for target.
photospline-gen_test_splines: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-gen_test_splines
.PHONY : photospline-gen_test_splines

# fast build rule for target.
photospline-gen_test_splines/fast:
	$(MAKE) -f CMakeFiles/photospline-gen_test_splines.dir/build.make CMakeFiles/photospline-gen_test_splines.dir/build
.PHONY : photospline-gen_test_splines/fast

#=============================================================================
# Target rules for targets named photospline-test

# Build rule for target.
photospline-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-test
.PHONY : photospline-test

# fast build rule for target.
photospline-test/fast:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/build
.PHONY : photospline-test/fast

#=============================================================================
# Target rules for targets named photospline

# Build rule for target.
photospline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline
.PHONY : photospline

# fast build rule for target.
photospline/fast:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/build
.PHONY : photospline/fast

#=============================================================================
# Target rules for targets named photospline-inspect

# Build rule for target.
photospline-inspect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-inspect
.PHONY : photospline-inspect

# fast build rule for target.
photospline-inspect/fast:
	$(MAKE) -f CMakeFiles/photospline-inspect.dir/build.make CMakeFiles/photospline-inspect.dir/build
.PHONY : photospline-inspect/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named photospline-bench

# Build rule for target.
photospline-bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-bench
.PHONY : photospline-bench

# fast build rule for target.
photospline-bench/fast:
	$(MAKE) -f CMakeFiles/photospline-bench.dir/build.make CMakeFiles/photospline-bench.dir/build
.PHONY : photospline-bench/fast

#=============================================================================
# Target rules for targets named photospline-test-templated

# Build rule for target.
photospline-test-templated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-test-templated
.PHONY : photospline-test-templated

# fast build rule for target.
photospline-test-templated/fast:
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/build
.PHONY : photospline-test-templated/fast

#=============================================================================
# Target rules for targets named photospline-bench-templated

# Build rule for target.
photospline-bench-templated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-bench-templated
.PHONY : photospline-bench-templated

# fast build rule for target.
photospline-bench-templated/fast:
	$(MAKE) -f CMakeFiles/photospline-bench-templated.dir/build.make CMakeFiles/photospline-bench-templated.dir/build
.PHONY : photospline-bench-templated/fast

#=============================================================================
# Target rules for targets named photospline-eval

# Build rule for target.
photospline-eval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photospline-eval
.PHONY : photospline-eval

# fast build rule for target.
photospline-eval/fast:
	$(MAKE) -f CMakeFiles/photospline-eval.dir/build.make CMakeFiles/photospline-eval.dir/build
.PHONY : photospline-eval/fast

src/cinter/splinetable.o: src/cinter/splinetable.cpp.o

.PHONY : src/cinter/splinetable.o

# target to build an object file
src/cinter/splinetable.cpp.o:
	$(MAKE) -f CMakeFiles/cphotospline.dir/build.make CMakeFiles/cphotospline.dir/src/cinter/splinetable.cpp.o
.PHONY : src/cinter/splinetable.cpp.o

src/cinter/splinetable.i: src/cinter/splinetable.cpp.i

.PHONY : src/cinter/splinetable.i

# target to preprocess a source file
src/cinter/splinetable.cpp.i:
	$(MAKE) -f CMakeFiles/cphotospline.dir/build.make CMakeFiles/cphotospline.dir/src/cinter/splinetable.cpp.i
.PHONY : src/cinter/splinetable.cpp.i

src/cinter/splinetable.s: src/cinter/splinetable.cpp.s

.PHONY : src/cinter/splinetable.s

# target to generate assembly for a file
src/cinter/splinetable.cpp.s:
	$(MAKE) -f CMakeFiles/cphotospline.dir/build.make CMakeFiles/cphotospline.dir/src/cinter/splinetable.cpp.s
.PHONY : src/cinter/splinetable.cpp.s

src/core/bspline.o: src/core/bspline.cpp.o

.PHONY : src/core/bspline.o

# target to build an object file
src/core/bspline.cpp.o:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/bspline.cpp.o
.PHONY : src/core/bspline.cpp.o

src/core/bspline.i: src/core/bspline.cpp.i

.PHONY : src/core/bspline.i

# target to preprocess a source file
src/core/bspline.cpp.i:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/bspline.cpp.i
.PHONY : src/core/bspline.cpp.i

src/core/bspline.s: src/core/bspline.cpp.s

.PHONY : src/core/bspline.s

# target to generate assembly for a file
src/core/bspline.cpp.s:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/bspline.cpp.s
.PHONY : src/core/bspline.cpp.s

src/core/bspline_multi.o: src/core/bspline_multi.cpp.o

.PHONY : src/core/bspline_multi.o

# target to build an object file
src/core/bspline_multi.cpp.o:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/bspline_multi.cpp.o
.PHONY : src/core/bspline_multi.cpp.o

src/core/bspline_multi.i: src/core/bspline_multi.cpp.i

.PHONY : src/core/bspline_multi.i

# target to preprocess a source file
src/core/bspline_multi.cpp.i:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/bspline_multi.cpp.i
.PHONY : src/core/bspline_multi.cpp.i

src/core/bspline_multi.s: src/core/bspline_multi.cpp.s

.PHONY : src/core/bspline_multi.s

# target to generate assembly for a file
src/core/bspline_multi.cpp.s:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/bspline_multi.cpp.s
.PHONY : src/core/bspline_multi.cpp.s

src/core/convolve.o: src/core/convolve.cpp.o

.PHONY : src/core/convolve.o

# target to build an object file
src/core/convolve.cpp.o:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/convolve.cpp.o
.PHONY : src/core/convolve.cpp.o

src/core/convolve.i: src/core/convolve.cpp.i

.PHONY : src/core/convolve.i

# target to preprocess a source file
src/core/convolve.cpp.i:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/convolve.cpp.i
.PHONY : src/core/convolve.cpp.i

src/core/convolve.s: src/core/convolve.cpp.s

.PHONY : src/core/convolve.s

# target to generate assembly for a file
src/core/convolve.cpp.s:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/convolve.cpp.s
.PHONY : src/core/convolve.cpp.s

src/core/fitsio.o: src/core/fitsio.cpp.o

.PHONY : src/core/fitsio.o

# target to build an object file
src/core/fitsio.cpp.o:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/fitsio.cpp.o
.PHONY : src/core/fitsio.cpp.o

src/core/fitsio.i: src/core/fitsio.cpp.i

.PHONY : src/core/fitsio.i

# target to preprocess a source file
src/core/fitsio.cpp.i:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/fitsio.cpp.i
.PHONY : src/core/fitsio.cpp.i

src/core/fitsio.s: src/core/fitsio.cpp.s

.PHONY : src/core/fitsio.s

# target to generate assembly for a file
src/core/fitsio.cpp.s:
	$(MAKE) -f CMakeFiles/photospline.dir/build.make CMakeFiles/photospline.dir/src/core/fitsio.cpp.s
.PHONY : src/core/fitsio.cpp.s

src/fitter/cholesky_solve.o: src/fitter/cholesky_solve.c.o

.PHONY : src/fitter/cholesky_solve.o

# target to build an object file
src/fitter/cholesky_solve.c.o:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/cholesky_solve.c.o
.PHONY : src/fitter/cholesky_solve.c.o

src/fitter/cholesky_solve.i: src/fitter/cholesky_solve.c.i

.PHONY : src/fitter/cholesky_solve.i

# target to preprocess a source file
src/fitter/cholesky_solve.c.i:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/cholesky_solve.c.i
.PHONY : src/fitter/cholesky_solve.c.i

src/fitter/cholesky_solve.s: src/fitter/cholesky_solve.c.s

.PHONY : src/fitter/cholesky_solve.s

# target to generate assembly for a file
src/fitter/cholesky_solve.c.s:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/cholesky_solve.c.s
.PHONY : src/fitter/cholesky_solve.c.s

src/fitter/glam.o: src/fitter/glam.c.o

.PHONY : src/fitter/glam.o

# target to build an object file
src/fitter/glam.c.o:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/glam.c.o
.PHONY : src/fitter/glam.c.o

src/fitter/glam.i: src/fitter/glam.c.i

.PHONY : src/fitter/glam.i

# target to preprocess a source file
src/fitter/glam.c.i:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/glam.c.i
.PHONY : src/fitter/glam.c.i

src/fitter/glam.s: src/fitter/glam.c.s

.PHONY : src/fitter/glam.s

# target to generate assembly for a file
src/fitter/glam.c.s:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/glam.c.s
.PHONY : src/fitter/glam.c.s

src/fitter/nnls.o: src/fitter/nnls.c.o

.PHONY : src/fitter/nnls.o

# target to build an object file
src/fitter/nnls.c.o:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/nnls.c.o
.PHONY : src/fitter/nnls.c.o

src/fitter/nnls.i: src/fitter/nnls.c.i

.PHONY : src/fitter/nnls.i

# target to preprocess a source file
src/fitter/nnls.c.i:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/nnls.c.i
.PHONY : src/fitter/nnls.c.i

src/fitter/nnls.s: src/fitter/nnls.c.s

.PHONY : src/fitter/nnls.s

# target to generate assembly for a file
src/fitter/nnls.c.s:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/nnls.c.s
.PHONY : src/fitter/nnls.c.s

src/fitter/splineutil.o: src/fitter/splineutil.c.o

.PHONY : src/fitter/splineutil.o

# target to build an object file
src/fitter/splineutil.c.o:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/splineutil.c.o
.PHONY : src/fitter/splineutil.c.o

src/fitter/splineutil.i: src/fitter/splineutil.c.i

.PHONY : src/fitter/splineutil.i

# target to preprocess a source file
src/fitter/splineutil.c.i:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/splineutil.c.i
.PHONY : src/fitter/splineutil.c.i

src/fitter/splineutil.s: src/fitter/splineutil.c.s

.PHONY : src/fitter/splineutil.s

# target to generate assembly for a file
src/fitter/splineutil.c.s:
	$(MAKE) -f CMakeFiles/spglam.dir/build.make CMakeFiles/spglam.dir/src/fitter/splineutil.c.s
.PHONY : src/fitter/splineutil.c.s

src/tools/bench.o: src/tools/bench.cpp.o

.PHONY : src/tools/bench.o

# target to build an object file
src/tools/bench.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-bench.dir/build.make CMakeFiles/photospline-bench.dir/src/tools/bench.cpp.o
	$(MAKE) -f CMakeFiles/photospline-bench-templated.dir/build.make CMakeFiles/photospline-bench-templated.dir/src/tools/bench.cpp.o
.PHONY : src/tools/bench.cpp.o

src/tools/bench.i: src/tools/bench.cpp.i

.PHONY : src/tools/bench.i

# target to preprocess a source file
src/tools/bench.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-bench.dir/build.make CMakeFiles/photospline-bench.dir/src/tools/bench.cpp.i
	$(MAKE) -f CMakeFiles/photospline-bench-templated.dir/build.make CMakeFiles/photospline-bench-templated.dir/src/tools/bench.cpp.i
.PHONY : src/tools/bench.cpp.i

src/tools/bench.s: src/tools/bench.cpp.s

.PHONY : src/tools/bench.s

# target to generate assembly for a file
src/tools/bench.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-bench.dir/build.make CMakeFiles/photospline-bench.dir/src/tools/bench.cpp.s
	$(MAKE) -f CMakeFiles/photospline-bench-templated.dir/build.make CMakeFiles/photospline-bench-templated.dir/src/tools/bench.cpp.s
.PHONY : src/tools/bench.cpp.s

src/tools/eval.o: src/tools/eval.cpp.o

.PHONY : src/tools/eval.o

# target to build an object file
src/tools/eval.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-eval.dir/build.make CMakeFiles/photospline-eval.dir/src/tools/eval.cpp.o
.PHONY : src/tools/eval.cpp.o

src/tools/eval.i: src/tools/eval.cpp.i

.PHONY : src/tools/eval.i

# target to preprocess a source file
src/tools/eval.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-eval.dir/build.make CMakeFiles/photospline-eval.dir/src/tools/eval.cpp.i
.PHONY : src/tools/eval.cpp.i

src/tools/eval.s: src/tools/eval.cpp.s

.PHONY : src/tools/eval.s

# target to generate assembly for a file
src/tools/eval.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-eval.dir/build.make CMakeFiles/photospline-eval.dir/src/tools/eval.cpp.s
.PHONY : src/tools/eval.cpp.s

src/tools/gen_test_splines.o: src/tools/gen_test_splines.cpp.o

.PHONY : src/tools/gen_test_splines.o

# target to build an object file
src/tools/gen_test_splines.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-gen_test_splines.dir/build.make CMakeFiles/photospline-gen_test_splines.dir/src/tools/gen_test_splines.cpp.o
.PHONY : src/tools/gen_test_splines.cpp.o

src/tools/gen_test_splines.i: src/tools/gen_test_splines.cpp.i

.PHONY : src/tools/gen_test_splines.i

# target to preprocess a source file
src/tools/gen_test_splines.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-gen_test_splines.dir/build.make CMakeFiles/photospline-gen_test_splines.dir/src/tools/gen_test_splines.cpp.i
.PHONY : src/tools/gen_test_splines.cpp.i

src/tools/gen_test_splines.s: src/tools/gen_test_splines.cpp.s

.PHONY : src/tools/gen_test_splines.s

# target to generate assembly for a file
src/tools/gen_test_splines.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-gen_test_splines.dir/build.make CMakeFiles/photospline-gen_test_splines.dir/src/tools/gen_test_splines.cpp.s
.PHONY : src/tools/gen_test_splines.cpp.s

src/tools/inspect.o: src/tools/inspect.cpp.o

.PHONY : src/tools/inspect.o

# target to build an object file
src/tools/inspect.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-inspect.dir/build.make CMakeFiles/photospline-inspect.dir/src/tools/inspect.cpp.o
.PHONY : src/tools/inspect.cpp.o

src/tools/inspect.i: src/tools/inspect.cpp.i

.PHONY : src/tools/inspect.i

# target to preprocess a source file
src/tools/inspect.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-inspect.dir/build.make CMakeFiles/photospline-inspect.dir/src/tools/inspect.cpp.i
.PHONY : src/tools/inspect.cpp.i

src/tools/inspect.s: src/tools/inspect.cpp.s

.PHONY : src/tools/inspect.s

# target to generate assembly for a file
src/tools/inspect.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-inspect.dir/build.make CMakeFiles/photospline-inspect.dir/src/tools/inspect.cpp.s
.PHONY : src/tools/inspect.cpp.s

test/test_eval.o: test/test_eval.cpp.o

.PHONY : test/test_eval.o

# target to build an object file
test/test_eval.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_eval.cpp.o
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_eval.cpp.o
.PHONY : test/test_eval.cpp.o

test/test_eval.i: test/test_eval.cpp.i

.PHONY : test/test_eval.i

# target to preprocess a source file
test/test_eval.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_eval.cpp.i
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_eval.cpp.i
.PHONY : test/test_eval.cpp.i

test/test_eval.s: test/test_eval.cpp.s

.PHONY : test/test_eval.s

# target to generate assembly for a file
test/test_eval.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_eval.cpp.s
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_eval.cpp.s
.PHONY : test/test_eval.cpp.s

test/test_fit.o: test/test_fit.cpp.o

.PHONY : test/test_fit.o

# target to build an object file
test/test_fit.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/test/test_fit.cpp.o
.PHONY : test/test_fit.cpp.o

test/test_fit.i: test/test_fit.cpp.i

.PHONY : test/test_fit.i

# target to preprocess a source file
test/test_fit.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/test/test_fit.cpp.i
.PHONY : test/test_fit.cpp.i

test/test_fit.s: test/test_fit.cpp.s

.PHONY : test/test_fit.s

# target to generate assembly for a file
test/test_fit.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/test/test_fit.cpp.s
.PHONY : test/test_fit.cpp.s

test/test_fitsio.o: test/test_fitsio.cpp.o

.PHONY : test/test_fitsio.o

# target to build an object file
test/test_fitsio.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_fitsio.cpp.o
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_fitsio.cpp.o
.PHONY : test/test_fitsio.cpp.o

test/test_fitsio.i: test/test_fitsio.cpp.i

.PHONY : test/test_fitsio.i

# target to preprocess a source file
test/test_fitsio.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_fitsio.cpp.i
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_fitsio.cpp.i
.PHONY : test/test_fitsio.cpp.i

test/test_fitsio.s: test/test_fitsio.cpp.s

.PHONY : test/test_fitsio.s

# target to generate assembly for a file
test/test_fitsio.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_fitsio.cpp.s
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_fitsio.cpp.s
.PHONY : test/test_fitsio.cpp.s

test/test_main.o: test/test_main.cpp.o

.PHONY : test/test_main.o

# target to build an object file
test/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/test/test_main.cpp.o
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_main.cpp.o
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_main.cpp.o
.PHONY : test/test_main.cpp.o

test/test_main.i: test/test_main.cpp.i

.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/test/test_main.cpp.i
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_main.cpp.i
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_main.cpp.i
.PHONY : test/test_main.cpp.i

test/test_main.s: test/test_main.cpp.s

.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/photospline-test-fit.dir/build.make CMakeFiles/photospline-test-fit.dir/test/test_main.cpp.s
	$(MAKE) -f CMakeFiles/photospline-test.dir/build.make CMakeFiles/photospline-test.dir/test/test_main.cpp.s
	$(MAKE) -f CMakeFiles/photospline-test-templated.dir/build.make CMakeFiles/photospline-test-templated.dir/test/test_main.cpp.s
.PHONY : test/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... check"
	@echo "... photospline-test-fit"
	@echo "... spglam"
	@echo "... cphotospline"
	@echo "... install"
	@echo "... photospline-gen_test_splines"
	@echo "... photospline-test"
	@echo "... test"
	@echo "... photospline"
	@echo "... photospline-inspect"
	@echo "... uninstall"
	@echo "... photospline-bench"
	@echo "... photospline-test-templated"
	@echo "... photospline-bench-templated"
	@echo "... photospline-eval"
	@echo "... src/cinter/splinetable.o"
	@echo "... src/cinter/splinetable.i"
	@echo "... src/cinter/splinetable.s"
	@echo "... src/core/bspline.o"
	@echo "... src/core/bspline.i"
	@echo "... src/core/bspline.s"
	@echo "... src/core/bspline_multi.o"
	@echo "... src/core/bspline_multi.i"
	@echo "... src/core/bspline_multi.s"
	@echo "... src/core/convolve.o"
	@echo "... src/core/convolve.i"
	@echo "... src/core/convolve.s"
	@echo "... src/core/fitsio.o"
	@echo "... src/core/fitsio.i"
	@echo "... src/core/fitsio.s"
	@echo "... src/fitter/cholesky_solve.o"
	@echo "... src/fitter/cholesky_solve.i"
	@echo "... src/fitter/cholesky_solve.s"
	@echo "... src/fitter/glam.o"
	@echo "... src/fitter/glam.i"
	@echo "... src/fitter/glam.s"
	@echo "... src/fitter/nnls.o"
	@echo "... src/fitter/nnls.i"
	@echo "... src/fitter/nnls.s"
	@echo "... src/fitter/splineutil.o"
	@echo "... src/fitter/splineutil.i"
	@echo "... src/fitter/splineutil.s"
	@echo "... src/tools/bench.o"
	@echo "... src/tools/bench.i"
	@echo "... src/tools/bench.s"
	@echo "... src/tools/eval.o"
	@echo "... src/tools/eval.i"
	@echo "... src/tools/eval.s"
	@echo "... src/tools/gen_test_splines.o"
	@echo "... src/tools/gen_test_splines.i"
	@echo "... src/tools/gen_test_splines.s"
	@echo "... src/tools/inspect.o"
	@echo "... src/tools/inspect.i"
	@echo "... src/tools/inspect.s"
	@echo "... test/test_eval.o"
	@echo "... test/test_eval.i"
	@echo "... test/test_eval.s"
	@echo "... test/test_fit.o"
	@echo "... test/test_fit.i"
	@echo "... test/test_fit.s"
	@echo "... test/test_fitsio.o"
	@echo "... test/test_fitsio.i"
	@echo "... test/test_fitsio.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

