#ifndef PHOTOSPLINE_CONFIG_H
#define PHOTOSPLINE_CONFIG_H

#define PHOTOSPLINE_VERSION 2.0.0
#define PHOTOSPLINE_MAJOR_VERSION 2
#define PHOTOSPLINE_MINOR_VERSION 0
#define PHOTOSPLINE_PATCH_VERSION 0

#endif // PHOTOSPLINE_CONFIG_H
